### ISSUE TITLE
Write contributing guide

### ISSUE THREAD

**Issue by mpfl** [au-research/FAIR-data-101-training#1]
We need some information for people who would like to contribute to this material.

**Comment by ragamouf** [comment]
completed, using template from https://github.com/au-research/ARDC-23-things/commit/7de3dd82160d846c04fb939d6b42eab0e9e45ca6

**Comment by ragamouf** [comment]
@NicholaBurton @mpfl Did Julia, Mingfang or Kerry support community discussions?

**Comment by NicholaBurton** [comment]
Ming did. Julia sat in on some community discussions but didn't have an official supporting role.
