### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by mpfl** [au-research/FAIR-data-101-training#28]
Has GitHub implemented a mechanism to do this easily?

**Comment by mpfl** [comment]
No, GitHub has not yet implemented a mechanism to do this easily. Apparently it will exist by the end of 2020.

**Comment by orchid00** [comment]
it is currently Main 
you can close this issue @mpfl

**Comment by mpfl** [comment]
Yeah, I think I got sick of waiting for the automated method and did it myself.
