### ISSUE TITLE
Update README.md with a little bit about FAIR Data 101 Express

### ISSUE THREAD

**Issue by mpfl** [au-research/FAIR-data-101-training#32]

**Comment by ragamouf** [comment]
done - submitted PR #33

**Comment by mpfl** [comment]
Issue shouldn't be closed until pull request is merged ;-)

**Comment by mpfl** [comment]
Addressed by PR #33

**Comment by ragamouf** [comment]
er, can we close this issue now?

**Comment by mpfl** [comment]
Ugh. The _one_ button I forget to press.
