### ISSUE TITLE
Link from public page to github repo?

### ISSUE THREAD

**Issue by ragamouf** [au-research/FAIR-data-101-training#36]
Carpentries template has "Improve this page" on their lessons, which takes you to the github repository page. Can we add something like that to the public FAIR 101 page?
This also makes me realise the repo has citation, contribution and reuse pages, but these are not on the public gh-pages version?

**Comment by orchid00** [comment]
@mpfl can you add this to the training template please?

**Comment by mpfl** [comment]
I've already added an "improve this page" link to the [training-template itself](https://github.com/au-research/training-template), but haven't brought it across to FAIR Data 101. The layout of this lesson is a bit different to our newer lessons like First step to FAIR and GitHub Training. I'll see what I can do.

**Comment by mpfl** [comment]
Done!
